name: "inecuatie2"
title: "inecuatie2"
time_limit: 0.2
memory_limit: 1
n_input: 20
score_mode: max
token_mode: disabled
max_submission_number: 15
min_submission_interval: 30
infile: "stdin"
outfile: "stdout"
primary_language: "ro"